local gh = function(repository)
  return 'https://github.com/' .. repository
end

return {
  { src = gh 'L3MON4D3/LuaSnip', version = 'master' },
  { src = gh 'MagicDuck/grug-far.nvim', version = 'main' },
  { src = gh 'MunifTanjim/nui.nvim', version = 'main' },
  { src = gh 'NMAC427/guess-indent.nvim', version = 'main' },
  { src = gh 'NeogitOrg/neogit', version = 'master' },
  { src = gh 'OXY2DEV/markview.nvim', version = 'main' },
  { src = gh 'akinsho/toggleterm.nvim', version = 'main' },
  { src = gh 'catppuccin/nvim', name = 'catppuccin', version = 'main' },
  { src = gh 'davidgranstrom/scnvim', version = 'main' },
  { src = gh 'echasnovski/mini.nvim', version = 'main' },
  { src = gh 'folke/lazydev.nvim', version = 'main' },
  { src = gh 'folke/todo-comments.nvim', version = 'main' },
  { src = gh 'folke/which-key.nvim', version = 'main' },
  { src = gh 'j-hui/fidget.nvim', version = 'main' },
  { src = gh 'krisajenkins/neojj', version = 'main' },
  { src = gh 'leoluz/nvim-dap-go', version = 'main' },
  { src = gh 'lewis6991/gitsigns.nvim', version = 'main' },
  { src = gh 'lukas-reineke/indent-blankline.nvim', version = 'master' },
  { src = gh 'm00qek/baleia.nvim', version = 'main' },
  { src = gh 'mfussenegger/nvim-dap', version = 'master' },
  { src = gh 'mfussenegger/nvim-dap-python', version = 'master' },
  { src = gh 'mrcjkb/rustaceanvim', version = 'master' },
  { src = gh 'neovim/nvim-lspconfig', version = 'master' },
  { src = gh 'nvim-lua/plenary.nvim', version = 'master' },
  { src = gh 'nvim-mini/mini.icons', version = 'main' },
  { src = gh 'nvim-neo-tree/neo-tree.nvim', version = 'main' },
  { src = gh 'nvim-neotest/nvim-nio', version = 'master' },
  { src = gh 'nvim-telescope/telescope-fzf-native.nvim', version = 'main' },
  { src = gh 'nvim-telescope/telescope-ui-select.nvim', version = 'master' },
  { src = gh 'nvim-telescope/telescope.nvim', version = 'master' },
  { src = gh 'nvim-tree/nvim-web-devicons', version = 'master' },
  { src = gh 'nvim-treesitter/nvim-treesitter', version = 'main' },
  { src = gh 'ph1losof/ecolog.nvim', version = 'main' },
  { src = gh 'rafamadriz/friendly-snippets', version = 'main' },
  { src = gh 'rcarriga/nvim-dap-ui', version = 'master' },
  { src = gh 'saghen/blink.cmp', version = 'main' },
  { src = gh 'sindrets/diffview.nvim', version = 'main' },
  { src = gh 'stevearc/conform.nvim', version = 'master' },
  { src = gh 'stevearc/oil.nvim', version = 'master' },
  { src = gh 'supermaven-inc/supermaven-nvim', version = 'main' },
  { src = gh 'tidalcycles/vim-tidal', version = 'master' },
  { src = gh 'yetone/avante.nvim', version = 'main' },
  { src = gh 'windwp/nvim-autopairs', version = 'master' },
  { src = gh 'mbbill/undotree', version = 'master' },
}
